version: '3.8'

services:
  app:
    build: .
    ports:
      # HTTPサーバー
      - "3000:3000"  
      # WebSocketサーバー
      - "5000:5000"  
    volumes:
      - .:/app
    environment:
      NODE_ENV: development
    depends_on:
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat_app
      MYSQL_USER: root
      # MYSQL_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

networks:
  default:
    driver: bridge

volumes:
  db_data:
